"""
MCP Approach -- Multi-Agent Workflow (Tool-Calling Mode)

This is the MCP approach entry point. Instead of generating a complete workflow script
(codegen) and executing it (executor), this approach uses an explorer agent that
interactively calls tools to execute each workflow task step by step in a local venv.

Pipeline:
    orchestrator -> planner -> installer -> explorer -> end

Usage:
    python agent_mcp.py --paper 1 --goal "Reproduce this workflow..."
    python agent_mcp.py --paper YildizO_RAPIDS.pdf --goal "..."
"""

import os
import base64
import json
import mimetypes
import operator
import re
import subprocess
import time
import warnings
from datetime import datetime
from typing import Annotated, Literal, Sequence
from typing_extensions import TypedDict
from pydantic import BaseModel
from pypdf import PdfReader
warnings.filterwarnings("ignore", module="pypdf")
from dotenv import load_dotenv
from rich.console import Console
from rich.panel import Panel
from langchain_openai import ChatOpenAI
from langchain_core.messages import BaseMessage, HumanMessage, SystemMessage
from langgraph.graph import StateGraph, END
from langgraph.graph.message import add_messages

from mcp_explorer import explorer
from trace_logger import tracer, extract_usage, message_to_dict

load_dotenv()

console = Console()

_run_log_path: str = "" # path for logging run-level events in JSONL format; only in orchestrator to record routing decisions


# __ LLM ______________________________________________________________________
model = ChatOpenAI(model=os.getenv("MODEL_NAME", "claudesonnet46"))


# __ Agent State _______________________________________________________________

class AgentState(TypedDict):
    messages:              Annotated[Sequence[BaseMessage], add_messages]
    goal:                  str
    pdf_path:              str
    literature_findings:   list[str]
    stack_decision:        list[str]
    tasks:                 list[str]
    exploration_log:       list[dict]       # explorer output (tool call records)
    selected_data_files:   list[str]        # filenames chosen from data/ at startup
    requirements_content:  str
    requirements_approved: bool
    image_path:            str              # path to user-uploaded image for planning (optional)
    current_step:          str
    orchestrator_feedback: str
    next:                  str
    planner_revisions:     int
    installer_revisions:   int
    explorer_revisions:    int
    engine:                str              # workflow engine: "parsl", "pycompss", etc.
    env:                   str              # execution environment: "local" or "hpc"


# __ Pydantic Schemas __________________________________________________________

class OrchestratorOutput(BaseModel):
    reasoning:           str
    next:                  Literal["planner", "installer", "explorer", "end"]
    feedback:              str
    requirements_approved: bool = False
    skill_requests:        list[str] = []

class PlannerOutput(BaseModel):
    literature_findings: list[str]
    stack_decision:      list[str]
    tasks:               list[str]
    skill_requests:      list[str] = []

class InstallerOutput(BaseModel):
    requirements_content: str


# __ Agent Prompts _____________________________________________________________

ORCHESTRATOR_SYSTEM_PROMPT = """\
Your agent skill file contains your full operating instructions. Follow them.

Return ONLY a valid JSON object with exactly these keys:
- reasoning:           str -- your analysis of the current state
- next:                "planner" | "installer" | "explorer" | "end"
- feedback:            str -- specific actionable feedback for the receiving agent, or "" if proceeding normally
- requirements_approved: bool -- true ONLY when approving pending requirements.txt, false in all other cases
- skill_requests:      list[str] -- skill paths to load (first call only; empty on subsequent calls)
\
"""

PLANNER_PROMPT = """\
Your agent skill file contains your full operating instructions. Follow them.

Return ONLY a valid JSON object with exactly these keys:
- literature_findings: list[str] -- specific, quantitative facts extracted from the paper
- stack_decision:      list[str] -- packages to install into the local venv
- tasks:               list[str] -- ordered, Python-API-level implementation steps
- skill_requests:      list[str] -- skill paths to load (first call only; empty on subsequent calls)

No markdown, no code fences, no explanation outside the JSON.

IMPORTANT CONSTRAINTS ON TASKS:
- Do NOT include tasks to reproduce performance benchmarks, scaling plots, or timing
  comparisons from the paper unless the environment knowledge confirms the resources exist.
- Do NOT include tasks that fabricate or simulate fake benchmark data to mimic the
  paper's performance results.
- DO include tasks that reproduce the actual scientific computation (simulation,
  analysis, visualization) using data generated by the workflow itself.
- All visualizations must use data produced by the workflow, not hardcoded values
  from the paper.
- Follow the environment knowledge injected into your context (local or HPC) for
  what parallelism, MPI, and job launcher commands are appropriate.

HANDLING ORCHESTRATOR FEEDBACK:
If the input ends with "Orchestrator feedback", fix every issue raised before returning.\
"""


# __ Project layout (injected into context) ____________________________________
######################################################################## Project layout -- this is injected into the system prompt for all agents, so they understand where to read/write files and how the repo maps to runtime paths. Update as needed for your project. ################################################################

PROJECT_LAYOUT = """\
Repo directory tree -- the repo root is mapped to /app/ at runtime:

/app/                                  <- repo root
+-- agent_mcp.py
+-- mcp_tools.py
+-- mcp_explorer.py
+-- requirements.txt
+-- .env
+-- data/
|   +-- in.watbox                      <- LAMMPS input script
|   +-- data.init                      <- LAMMPS initial atom positions
|   +-- AW.tersoff                     <- LAMMPS force field parameters
+-- Literature/
|   +-- *.pdf
+-- builds/                            <- installer-generated requirements
|   +-- requirements.txt               <- venv package list
+-- work/                              <- explorer output goes here
    +-- run0/                          <- default working directory
\
"""

HOST_REPO_PATH = os.environ.get("HOST_REPO_PATH", os.path.dirname(os.path.abspath(__file__)))


# __ Structured output helper __________________________________________________

def _invoke_structured(llm, schema, messages, agent_name, retries=5):
    """Call llm and parse the response as schema, tolerating preamble text before the JSON block."""
    import json as _json, re as _re
    last_err = None
    model_name = getattr(llm, "model_name", None) or os.getenv("MODEL_NAME", "")
    msg_dicts = [message_to_dict(m) for m in messages]
    for attempt in range(retries):
        _t0 = time.time()
        response = llm.invoke(messages)
        latency_s = round(time.time() - _t0, 2)
        text = response.content if hasattr(response, "content") else str(response)
        usage = extract_usage(response)
        tracer.log_llm_call(
            agent_name, model_name, msg_dicts, text,
            input_tokens=usage["input_tokens"], output_tokens=usage["output_tokens"],
            total_tokens=usage["total_tokens"], latency_s=latency_s, attempt=attempt + 1,
        )
        match = _re.search(r'\{.*\}', text, _re.DOTALL)
        if not match:
            last_err = ValueError(f"No JSON object found in model response:\n{text[:500]}")
            console.print(f"[yellow][_invoke_structured] attempt {attempt+1}: no JSON found, retrying...[/yellow]")
            continue
        try:
            return schema.model_validate(_json.loads(match.group(0)))
        except (_json.JSONDecodeError, Exception) as e:
            last_err = e
            console.print(f"[yellow][_invoke_structured] attempt {attempt+1}: parse error ({e}), retrying...[/yellow]")
    raise last_err


# __ Skill file helpers ________________________________________________________
############################################################################# SKILL FILE MANAGEMENT: read .SKILL.md files for orchestrator and planner, with support for sub-skill requests #################################

_SKILLS_ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "skills")

def _read_skill(rel_path: str, agent_name: str) -> str:
    """Read skills/<rel_path>.SKILL.md -- returns '' if not found. Logs the load attempt."""
    full = os.path.join(_SKILLS_ROOT, rel_path + ".SKILL.md")
    found = os.path.isfile(full)
    tracer.log_skill_load(agent_name, rel_path, found)
    if found:
        with open(full) as f:
            return f.read()
    return ""

_ENV_KNOWLEDGE = {
    "local": "knowledge/local",
    "hpc":   "knowledge/lcrc",
}

def _env_knowledge(env: str, agent_name: str) -> str:
    """Return the environment knowledge skill content for the given env."""
    skill_key = _ENV_KNOWLEDGE.get(env, "knowledge/local")
    return _read_skill(skill_key, agent_name)

def _slugify(path: str) -> str:
    """Turn a file path into a stable run-metadata id, e.g. for paper_id."""
    base = os.path.splitext(os.path.basename(path))[0] if path else "no_paper"
    slug = re.sub(r"[^a-zA-Z0-9_-]+", "_", base).strip("_")
    return slug or "no_paper"


def _list_skills(folder: str) -> list:
    """List available names in skills/<folder>/: subdirectory names AND .SKILL.md base names."""
    d = os.path.join(_SKILLS_ROOT, folder)
    if not os.path.isdir(d):
        return []
    results = []
    for name in os.listdir(d):
        if os.path.isdir(os.path.join(d, name)):
            results.append(name)
        elif name.endswith(".SKILL.md"):
            results.append(os.path.splitext(name)[0])
    return results


# __ Nodes _____________________________________________________________________

############################################################################# ORCHESTRATOR ##############################################################

def orchestrator(state: AgentState) -> dict:
    console.print("\n[dim cyan][orchestrator] reviewing state...[/dim cyan]")
    tracer.log_agent_start("orchestrator")         ########### insert TRACER ##########
    tracer.log_agent_input("orchestrator", {       ########### insert TRACER ##########
        "current_step": state.get("current_step", ""),
        "goal": state.get("goal", ""),
        "has_findings": bool(state.get("literature_findings")),
        "has_tasks": bool(state.get("tasks")),
        "has_exploration_log": bool(state.get("exploration_log")),
    })

    revisions = {
        "planner":   state.get("planner_revisions",   0),
        "installer": state.get("installer_revisions", 0),
        "explorer":  state.get("explorer_revisions",  0),
    }
    if any(revisions.values()):
        rev_str = " | ".join(f"{k}: {v}" for k, v in revisions.items() if v > 0)
        console.print(f"[dim yellow][orchestrator] revision counts -- {rev_str}[/dim yellow]")

    parts = [f"Goal: {state['goal']}", f"Current step: {state['current_step']}"]
    if state.get("literature_findings"):
        parts.append(f"Literature findings ({len(state['literature_findings'])} items):\n" +
                     "\n".join(f"  - {f}" for f in state["literature_findings"]))
    if state.get("stack_decision"):
        parts.append(f"Stack: {state['stack_decision']}")
    if state.get("tasks"):
        parts.append(f"Tasks ({len(state['tasks'])}):\n" +
                     "\n".join(f"  {i+1}. {t}" for i, t in enumerate(state["tasks"])))
    if state.get("requirements_content"):
        parts.append(f"requirements.txt:\n{state['requirements_content']}")
    if state.get("exploration_log"):
        # Summarize exploration log for orchestrator
        log = state["exploration_log"]
        total = len(log)
        successes = sum(1 for e in log if e.get("succeeded", False))
        failures = total - successes
        parts.append(f"Exploration: {total} tool calls, {successes} succeeded, {failures} failed")
        # Include last few entries for detail
        for entry in log[-5:]:
            status_str = "OK" if entry.get("succeeded", False) else "FAILED"
            parts.append(f"  [{entry['tool']}] {status_str} - {entry.get('result', '')[:200]}")

    # Build system prompt: base skill + env knowledge + available skill index + core prompt
    _base = _read_skill("agents/orchestrator", "orchestrator")
    _env_kn = _env_knowledge(state.get("env", "local"), "orchestrator")
    _uc = _list_skills("use_cases")
    _sys = _list_skills("systems")
    _index = (f"\n\nAvailable skill contexts (set in skill_requests to load):"
              f"\n  use_cases: {_uc}  -- request as \"use_cases/<name>/orchestrator\""
              f"\n  systems:   {_sys}  -- request as \"systems/<name>\"") if (_uc or _sys) else ""
    _env_section = f"\n\n=== Environment Knowledge ===\n{_env_kn}" if _env_kn else ""
    _sys_prompt = (_base + _env_section + _index + "\n\n---\n\n" + ORCHESTRATOR_SYSTEM_PROMPT) if _base else ORCHESTRATOR_SYSTEM_PROMPT
    _human = "\n\n".join(parts)

    result: OrchestratorOutput = _invoke_structured(model, OrchestratorOutput, [
        SystemMessage(content=_sys_prompt),
        HumanMessage(content=_human),
    ], "orchestrator")

    # Two-pass: if sub-skills requested, load them and re-invoke once
    if result.skill_requests:
        _sub = "\n\n".join(filter(None, (_read_skill(r, "orchestrator") for r in result.skill_requests)))
        if _sub:
            _enriched = _sys_prompt + f"\n\n=== Loaded Skills ===\n{_sub}\n\n(Final pass -- do not set skill_requests.)"
            result = _invoke_structured(model, OrchestratorOutput, [
                SystemMessage(content=_enriched),
                HumanMessage(content=_human),
            ], "orchestrator")

    # Hard overrides: lock routing at deterministic transition points
    if state.get("current_step") == "installer_requirements_pending_approval":
        result.next = "installer"
    elif state.get("current_step") == "installer_complete":
        result.next = "explorer"
    elif state.get("current_step") == "explorer_complete":
        # After explorer completes, check if key outputs exist before deciding to re-run.
        # If the explorer produced results (even partial), prefer ending over re-running.
        log = state.get("exploration_log", [])
        successes = sum(1 for e in log if e.get("succeeded", False))
        if successes > 0 and result.next == "explorer":
            # Explorer already ran and produced some results -- check if re-run is justified
            explorer_revs = state.get("explorer_revisions", 0)
            if explorer_revs >= 1:
                console.print("[dim yellow][orchestrator] explorer already revised once with results -- ending[/dim yellow]")
                result.next = "end"

    panel_body = f"[bold]Routing to:[/bold] [green]{result.next}[/green]\n\n[bold]Reasoning:[/bold]\n{result.reasoning}"
    if result.feedback:
        panel_body += f"\n\n[bold]Feedback to {result.next}:[/bold]\n[yellow]{result.feedback}[/yellow]"
    console.print(Panel(panel_body, title="[bold cyan]Orchestrator Decision[/bold cyan]", border_style="cyan"))

    # Only wriiten in orchestrator, planner/installer don't use it 
    if _run_log_path:
        with open(_run_log_path, "a") as _lf:
            _lf.write(json.dumps({
                "ts":         datetime.now().isoformat(),
                "from_step":  state.get("current_step"),
                "routing_to": result.next,
                "revisions":  revisions,
                "feedback":   result.feedback,
                "reasoning":  result.reasoning[:500],
            }) + "\n")

    already_ran = {
        "planner":   bool(state.get("literature_findings")),
        "installer": bool(state.get("requirements_content")),
        "explorer":  bool(state.get("exploration_log")),
    }
    revision_update = {}
    if result.next in already_ran and already_ran[result.next]:
        key = f"{result.next}_revisions"
        revision_update[key] = state.get(key, 0) + 1
        console.print(f"[bold yellow][orchestrator] revision #{revision_update[key]} for {result.next}[/bold yellow]")
        tracer.log_replan(result.next, revision_update[key])

    state_update = {
        "next":                  result.next,
        "orchestrator_feedback": result.feedback,
        "requirements_approved": result.requirements_approved,
        "current_step":          f"orchestrator_routed_to_{result.next}",
        **revision_update,
    }

    tracer.log_routing("orchestrator", result.next, result.reasoning, result.feedback,                   ############# insert TRACER #############
                        payload_size=len(json.dumps(state_update, default=str)))
    tracer.log_agent_output("orchestrator", {"next": result.next, "feedback": result.feedback})          ############# insert TRACER #############
    tracer.log_agent_end("orchestrator")                                                                 ############# TRACER ENDS   #############

    return state_update


################################################################################## PLANNER ####################################################################################
def planner(state: AgentState) -> dict:
    try:
        console.print("\n[dim cyan][planner] reading PDF...[/dim cyan]")
        tracer.log_agent_start("planner")
        tracer.log_agent_input("planner", {"pdf_path": state["pdf_path"], "goal": state["goal"]})

        reader = PdfReader(state["pdf_path"])
        pdf_text = "\n".join(page.extract_text() for page in reader.pages if page.extract_text())
        console.print(f"[dim cyan][planner] loaded {len(reader.pages)} pages[/dim cyan]")

        feedback = state.get("orchestrator_feedback", "")
        feedback_section = (f"\n\nOrchestrator feedback -- address these issues before returning:\n{feedback}"
                            if feedback else "")

        # Build system prompt: base skill + env knowledge + available skill index + core prompt
        _base = _read_skill("agents/planner", "planner")
        _env_kn = _env_knowledge(state.get("env", "local"), "planner")
        _uc = _list_skills("use_cases")
        _sys = _list_skills("systems")
        _index = (f"\n\nAvailable skill contexts (set in skill_requests to load):"
                  f"\n  use_cases: {_uc}  -- request as \"use_cases/<name>/planner\""
                  f"\n  systems:   {_sys}  -- request as \"systems/<name>\"") if (_uc or _sys) else ""
        _env_section = f"\n\n=== Environment Knowledge ===\n{_env_kn}" if _env_kn else ""
        _sys_prompt = (_base + _env_section + _index + "\n\n---\n\n" + PLANNER_PROMPT) if _base else PLANNER_PROMPT
        _data_files = state.get("selected_data_files", [])
        _data_section = (f"\n\nAvailable input data files (in /app/data/):\n" +
                         "\n".join(f"  - {f}" for f in _data_files)) if _data_files else ""
        _human = f"Goal: {state['goal']}{_data_section}\n\nPaper:\n{pdf_text}{feedback_section}"

        # Build human message -- multimodal if an image was provided
        if state.get("image_path"):
            console.print("\n[dim cyan][planner] loading image...[/dim cyan]")
            with open(state["image_path"], "rb") as _f:
                _img_bytes = _f.read()
            _b64 = base64.b64encode(_img_bytes).decode()
            _mime, _ = mimetypes.guess_type(state["image_path"])
            _mime = _mime or "image/png"
            _human_msg = HumanMessage(content=[
                {"type": "image_url", "image_url": {"url": f"data:{_mime};base64,{_b64}"}},
                {"type": "text", "text": _human},
            ])
            console.print(f"[dim cyan][planner] image loaded ({_mime}, {len(_img_bytes)//1024}KB)[/dim cyan]")
        else:
            _human_msg = HumanMessage(content=_human)

        result: PlannerOutput = _invoke_structured(model, PlannerOutput, [
            SystemMessage(content=_sys_prompt),
            _human_msg,
        ], "planner")

        # Two-pass: if sub-skills requested, load them and re-invoke once
        if result.skill_requests:
            _sub = "\n\n".join(filter(None, (_read_skill(r, "planner") for r in result.skill_requests)))
            if _sub:
                _enriched = _sys_prompt + f"\n\n=== Loaded Skills ===\n{_sub}\n\n(Final pass -- do not set skill_requests.)"
                result = _invoke_structured(model, PlannerOutput, [
                    SystemMessage(content=_enriched),
                    _human_msg,
                ], "planner")

        console.print(f"[dim cyan][planner] produced {len(result.tasks)} tasks[/dim cyan]")

        findings = "\n".join(f"  [cyan]*[/cyan] {f}" for f in result.literature_findings)
        stack    = "\n".join(f"  [cyan]*[/cyan] {s}" for s in result.stack_decision)
        tasks    = "\n".join(f"  [bold]{i+1}.[/bold] {t}" for i, t in enumerate(result.tasks))
        console.print(Panel(
            f"[bold]Literature Findings[/bold]\n{findings}\n\n"
            f"[bold]Stack[/bold]\n{stack}\n\n"
            f"[bold]Tasks[/bold]\n{tasks}",
            title="[bold green]Planner Output[/bold green]",
            border_style="green",
        ))

        tracer.log_agent_output("planner", {
            "findings_count": len(result.literature_findings),
            "stack": result.stack_decision,
            "tasks_count": len(result.tasks),
            "tasks_preview": result.tasks[:3],
        })
        tracer.log_agent_end("planner")

        return {
            "literature_findings": result.literature_findings,
            "stack_decision":      result.stack_decision,
            "tasks":               result.tasks,
            "current_step":        "planner_complete",
        }
    except Exception as e:
        console.print(f"[red][planner] ERROR: {e}[/red]")
        raise

################################################################################################### INSTALLER ##############################################################

def installer(state: AgentState) -> dict:
    import sys
    try:
        tracer.log_agent_start("installer")
        build_dir         = os.path.join(os.path.dirname(os.path.abspath(__file__)), "builds")
        os.makedirs(build_dir, exist_ok=True)
        requirements_path = os.path.join(build_dir, "requirements.txt")

        if state.get("requirements_approved"):
            # __ Phase 2: requirements approved -- pip install into the current venv __
            with open(requirements_path) as f:
                packages = [ln.strip() for ln in f if ln.strip() and not ln.startswith("#")]

            if not packages:
                console.print("[dim cyan][installer] no packages to install[/dim cyan]")
                tracer.log_agent_output("installer", {"status": "no packages"})
                tracer.log_agent_end("installer")
                return {"current_step": "installer_complete"}

            console.print(f"[dim cyan][installer] pip installing {len(packages)} packages...[/dim cyan]")
            proc = subprocess.run(
                [sys.executable, "-m", "pip", "install"] + packages,
                capture_output=True, text=True, timeout=600,
            )
            if proc.returncode != 0:
                console.print(f"[yellow][installer] pip stderr:\n{proc.stderr[-2000:]}[/yellow]")
            else:
                console.print("[dim cyan][installer] packages ready[/dim cyan]")

            tracer.log_agent_output("installer", {"status": "packages installed", "count": len(packages)})
            tracer.log_agent_end("installer")
            return {"current_step": "installer_complete"}

        else:
            # __ Phase 1: read or generate requirements.txt, send to orchestrator for approval __
            feedback = state.get("orchestrator_feedback", "")
            stack = state.get("stack_decision", [])

            # If orchestrator rejected the previous requirements, regenerate from stack_decision
            # instead of reading the stale file from disk.
            if feedback and stack:
                console.print("[dim cyan][installer] orchestrator rejected previous requirements -- regenerating from stack_decision...[/dim cyan]")
                content = "\n".join(pkg for pkg in stack if pkg) + "\n"
                with open(requirements_path, "w") as f:
                    f.write(content)
                console.print(f"[dim cyan][installer] regenerated requirements.txt with {len(stack)} packages[/dim cyan]")
            elif os.path.isfile(requirements_path):
                console.print("[dim cyan][installer] reading existing requirements.txt...[/dim cyan]")
                with open(requirements_path) as f:
                    content = f.read()
            else:
                console.print("[dim cyan][installer] generating requirements.txt from stack_decision...[/dim cyan]")
                content = "\n".join(pkg for pkg in stack if pkg) + "\n"
                with open(requirements_path, "w") as f:
                    f.write(content)
                console.print(f"[dim cyan][installer] generated requirements.txt with {len(stack)} packages[/dim cyan]")

            console.print(Panel(
                content,
                title="[bold yellow]requirements.txt -- Pending Orchestrator Approval[/bold yellow]",
                border_style="yellow",
            ))
            console.print("[dim yellow][installer] waiting for orchestrator approval...[/dim yellow]")

            tracer.log_agent_output("installer", {"status": "pending approval", "packages": content.strip()})
            tracer.log_agent_end("installer")
            return {
                "requirements_content": content,
                "current_step":         "installer_requirements_pending_approval",
            }

    except Exception as e:
        console.print(f"[red][installer] ERROR: {e}[/red]")
        raise

# __ Graph _____________________________________________________________________
####################################################################################### LangGraph Nodes #######################################################################################################

def route_orchestrator(state: AgentState) -> str:
    return state["next"]


graph = StateGraph(AgentState)

graph.add_node("orchestrator", orchestrator)
graph.add_node("planner",      planner)
graph.add_node("installer",    installer)
graph.add_node("explorer",     explorer)

graph.set_entry_point("orchestrator")

graph.add_conditional_edges("orchestrator", route_orchestrator, {
    "planner":   "planner",
    "installer": "installer",
    "explorer":  "explorer",
    "end":       END,
})

graph.add_edge("planner",   "orchestrator")
graph.add_edge("installer", "orchestrator")
graph.add_edge("explorer",  "orchestrator")

app = graph.compile()


# __ Run _______________________________________________________________________
######################################################################### Console Terminal CLI DISPLAY AND RUN LOGGING ################################################################

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="MAW -- Multi-Agent Workflow (MCP Approach)")
    parser.add_argument("--paper", type=str, help="Path to the PDF paper or paper index (1-based)")
    parser.add_argument("--image", type=str, help="Path to image file (diagram/figure) to use for planning")
    parser.add_argument("--goal", type=str, help="Goal for the workflow")
    parser.add_argument("--engine", type=str, default="parsl",
                        choices=["parsl", "pycompss", "adios"],
                        help="Workflow engine to use (default: parsl)")
    parser.add_argument("--env", type=str, default="local",
                        choices=["local", "hpc"],
                        help="Execution environment: local (default) or hpc (LCRC/PBS)")
    parser.add_argument("--condition", type=str, default="B",
                        choices=["A", "B", "C"],
                        help="Ablation condition: A=no-skills, B=full (default), C=single-agent")
    parser.add_argument("--trial", type=int, default=1,
                        help="Trial number for repeated (paper, condition) runs (default: 1)")
    parser.add_argument("--domain", type=str, default="",
                        help="Paper domain label, e.g. molecular_nucleation (optional)")
    parser.add_argument("--eval-run", action="store_true",
                        help="Mark this as a real eval run (vs. a dev/smoke run). Requires --config-spec-ref.")
    parser.add_argument("--config-spec-ref", type=str, default=None,
                        help="Path/ID of the ground-truth config spec to grade this run against")
    parser.add_argument("--skip-data", action="store_true",
                        help="Skip the data/ file selection prompt -- agents get no local input data files "
                             "(use for use cases like cosmology that source their own inputs elsewhere)")
    args = parser.parse_args()

    if args.eval_run and not args.config_spec_ref:
        console.print("[red]--eval-run requires --config-spec-ref (a real eval run needs ground truth to grade against).[/red]")
        raise SystemExit(1)

    console.print(Panel(f"[bold blue]MAW -- Multi-Agent Workflow (MCP Approach)[/bold blue]\n[dim]Engine: {args.engine} | Env: {args.env}[/dim]", border_style="blue"))

    lit_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "Literature")
    os.makedirs(lit_dir, exist_ok=True)

    pdfs = [f for f in os.listdir(lit_dir) if f.lower().endswith(".pdf")]
    if not pdfs:
        console.print("[red]No PDFs found in the Literature/ folder. Add a paper and try again.[/red]")
        raise SystemExit(1)

    console.print("\n[bold]Available papers:[/bold]")
    for i, name in enumerate(pdfs, 1):
        console.print(f"  {i}. {name}")

    # Handle paper selection
    if args.paper:
        choice = args.paper
        try:
            pdf_path = os.path.join(lit_dir, pdfs[int(choice) - 1])
        except (ValueError, IndexError):
            pdf_path = os.path.join(lit_dir, choice)
            if not os.path.isfile(pdf_path):
                console.print(f"[red]Paper not found: {choice}[/red]")
                raise SystemExit(1)
    else:
        choice = input("\nSelect a paper by number: ").strip()
        try:
            pdf_path = os.path.join(lit_dir, pdfs[int(choice) - 1])
        except (ValueError, IndexError):
            console.print("[red]Invalid selection.[/red]")
            raise SystemExit(1)

    console.print(f"[dim]Selected: {os.path.basename(pdf_path)}[/dim]")

    # Handle image selection
    _IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".gif", ".webp"}
    images_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "images")
    os.makedirs(images_dir, exist_ok=True)

    if args.image:
        image_path = args.image if os.path.isabs(args.image) else os.path.join(images_dir, args.image)
        if not os.path.isfile(image_path):
            console.print(f"[red]Image not found: {args.image}[/red]")
            raise SystemExit(1)
        console.print(f"[dim]Image: {os.path.basename(image_path)}[/dim]")
    else:
        images = sorted(
            f for f in os.listdir(images_dir)
            if os.path.splitext(f)[1].lower() in _IMAGE_EXTS
        )
        if not images:
            image_path = ""
        else:
            console.print("\n[bold]Available images:[/bold]")
            for i, name in enumerate(images, 1):
                console.print(f"  {i}. {name}")
            console.print(f"  0. Skip -- no image")
            choice = input("\nSelect an image by number (or 0 to skip): ").strip()
            if choice == "0" or not choice:
                image_path = ""
                console.print("[dim]No image selected.[/dim]")
            else:
                try:
                    image_path = os.path.join(images_dir, images[int(choice) - 1])
                    console.print(f"[dim]Selected: {os.path.basename(image_path)}[/dim]")
                except (ValueError, IndexError):
                    console.print("[red]Invalid selection -- no image will be used.[/red]")
                    image_path = ""

    # Handle data file selection
    if args.skip_data:
        console.print("[dim]--skip-data set -- agents will have no local input data files.[/dim]")
        selected_data_files = []
    else:
        data_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")
        all_data_files = sorted(f for f in os.listdir(data_dir) if os.path.isfile(os.path.join(data_dir, f))) if os.path.isdir(data_dir) else []

        if not all_data_files:
            console.print("[yellow]No files found in data/ -- agents will have no input data.[/yellow]")
            selected_data_files = []
        else:
            console.print("\n[bold]Available data files:[/bold]")
            for i, name in enumerate(all_data_files, 1):
                console.print(f"  {i}. {name}")
            raw = input("\nSelect files by number (comma-separated, or Enter for all): ").strip()
            if not raw:
                selected_data_files = all_data_files
                console.print("[dim]Using all data files.[/dim]")
            else:
                selected_data_files = []
                for token in raw.split(","):
                    token = token.strip()
                    try:
                        selected_data_files.append(all_data_files[int(token) - 1])
                    except (ValueError, IndexError):
                        console.print(f"[yellow]Skipping invalid selection: {token!r}[/yellow]")
                if not selected_data_files:
                    console.print("[yellow]No valid files selected -- using all.[/yellow]")
                    selected_data_files = all_data_files
                else:
                    console.print(f"[dim]Selected: {', '.join(selected_data_files)}[/dim]")

    # Handle goal
    if args.goal:
        goal = args.goal
    else:
        goal = input("\nDescribe your goal for this workflow: ").strip()

    if not goal:
        console.print("[red]Goal cannot be empty.[/red]")
        raise SystemExit(1)

    runs_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "runs")
    os.makedirs(runs_dir, exist_ok=True)
    _run_id = datetime.now().strftime("%Y%m%d_%H%M%S")
    _run_log_path = os.path.join(runs_dir, _run_id + ".jsonl")
    console.print(f"[dim]Run log: {_run_log_path}[/dim]")

    initial_state = {
        "messages":              [],
        "goal":                  goal,
        "pdf_path":              pdf_path,
        "literature_findings":   [],
        "stack_decision":        [],
        "tasks":                 [],
        "exploration_log":       [],
        "selected_data_files":   selected_data_files,
        "requirements_content":  "",
        "requirements_approved": False,
        "image_path":            image_path,
        "current_step":          "start",
        "orchestrator_feedback": "",
        "next":                  "",
        "planner_revisions":     0,
        "installer_revisions":   0,
        "explorer_revisions":    0,
        "engine":                args.engine,
        "env":                   args.env,
    }

    trace_path = os.path.join(runs_dir, _run_id + "_trace.json")

    tracer.reset()   # brefor you run it, reset the tracer to clear any previous runs from the dashboard
    tracer.start_run(
        run_id=_run_id,
        condition=args.condition,
        trial=args.trial,
        paper_id=_slugify(pdf_path) if pdf_path else "no_paper",
        paper_path=pdf_path,
        domain=args.domain,
        framework=args.engine,
        env=args.env,
        goal=goal,
        model=os.getenv("MODEL_NAME", "claudeopus48"),
        is_eval_run=args.eval_run,
        config_spec_ref=args.config_spec_ref,
    )

    try:
        app.invoke(initial_state) # write the node functions to log to the tracer, and then invoke the graph with the initial state
        tracer.finalize_run("completed")
    except Exception as e:
        import traceback as _traceback
        tracer.log_run_error(type(e).__name__, str(e), _traceback.format_exc())
        tracer.finalize_run("failed")
        tracer.save(trace_path)
        console.print(f"[red]Run failed: {e}[/red]")
        console.print(f"[dim]Trace saved (partial): {trace_path}[/dim]")
        raise

    # Save trace
    tracer.save(trace_path)  #save the trace to a file for later analysis
    console.print(f"[dim]Trace saved: {trace_path}[/dim]")

    # Print interaction summary
    summary = tracer.get_summary()
    console.print(f"\n[bold]Trace Summary:[/bold]")
    console.print(f"  Agents: {', '.join(summary['agents_involved'])}")
    console.print(f"  Routing path: {' -> '.join(summary['routing_path'])}")
    console.print(f"  Tool calls: {summary['tool_calls']} ({summary['tool_successes']} succeeded)")
    console.print(f"  Total time: {summary['total_duration_s']}s")

################################################################### TOKEN USAGE SUMMARY (CHECK runs folder: xxxxxxxx_trace.json) ##################################################################)
    # Print token usage
    total_in = summary.get('total_input_tokens', 0)
    total_out = summary.get('total_output_tokens', 0)
    if total_in or total_out:
        console.print(f"\n[bold]Token Usage:[/bold]")
        console.print(f"  Input tokens:  {total_in:,}")
        console.print(f"  Output tokens: {total_out:,}")
        console.print(f"  Total tokens:  {total_in + total_out:,}")
        tokens_by_agent = summary.get('tokens_by_agent', {})
        if tokens_by_agent:
            console.print(f"  By agent:")
            for agent, count in sorted(tokens_by_agent.items()):
                console.print(f"    {agent}: {count:,}")

