"""
Clarifier -- turns a short, possibly vague natural-language request into a filled
6-slot task specification before planning begins (combination "d" / Desc-Only mode).

Design (locked with mentor):
- Fixed 6-slot questionnaire (below), asked in ONE round.
- The user may answer all / some / none of the slots.
- For every UNANSWERED slot, an LLM fills it with an explicit assumption.
- Every slot records its provenance: source = "user" | "agent", plus the value.
- Everything is traceable, so evaluation can compare the filled spec against a full
  ground-truth spec (the Molecular / Cosmology / Stokes descriptions).

Self-contained and UI-agnostic: `run_clarifier` takes an `answer_fn` (how answers
are collected) and a `fill_fn` (how gaps are filled), so the same logic drives a
real CLI user, a notebook, or a simulated user for batch evaluation.
"""
from __future__ import annotations

import json
from typing import Callable, Optional


# __ The fixed 6-slot questionnaire ____________________________________________
SLOTS: list[dict] = [
    {"key": "scientific_goal",
     "question": "Scientific goal -- what should the workflow compute or produce?"},
    {"key": "software",
     "question": "Method / software -- which simulator and analysis tools should each task use?"},
    {"key": "input_data",
     "question": "Input data -- is input data provided, or generated by the workflow itself?"},
    {"key": "parameters",
     "question": "Key parameters -- size, steps, resolution, MPI ranks (or leave blank for defaults)?"},
    {"key": "outputs_success",
     "question": "Expected outputs / success criteria -- what outputs, and how do we know it worked?"},
    {"key": "environment",
     "question": "Environment & scale -- local or HPC, and how many processes / ranks / nodes?"},
]

SLOT_KEYS = [s["key"] for s in SLOTS]


# __ Answer collectors (pluggable) _____________________________________________

def cli_answer_fn(slot: dict) -> str:
    """Ask one slot on the command line. Empty input == 'not answered'."""
    return input(f"  [{slot['key']}] {slot['question']}\n  > ").strip()


def make_simulated_user_answer_fn(full_spec: dict, answer_keys: Optional[set] = None) -> Callable[[dict], str]:
    """Build an answer_fn that plays a 'simulated user' for batch evaluation.

    full_spec: {slot_key: ground-truth answer}. answer_keys: which slots this
    simulated user answers (rest left blank -> agent must fill them). None = answer all it knows.
    """
    def _answer(slot: dict) -> str:
        key = slot["key"]
        if answer_keys is not None and key not in answer_keys:
            return ""
        return str(full_spec.get(key, "")).strip()
    return _answer


# __ Core ______________________________________________________________________

def run_clarifier(seed_prompt: str,
                  answer_fn: Callable[[dict], str] = cli_answer_fn,
                  fill_fn: Optional[Callable[[str, dict, list], dict]] = None,
                  detect_fn: Optional[Callable[[str], dict]] = None) -> dict:
    """Clarify an underspecified request, asking ONLY the missing slots.

    1. detect_fn analyses the prompt -> which of the 6 slots it already covers.
    2. Ask the user ONLY the slots the prompt did not cover.
    3. Slots the user still leaves blank are filled by the LLM (assumptions).

    Per-slot provenance is one of: "prompt" (already in the request),
    "user" (answered a clarifying question), "agent" (assumed). Returns the
    filled slots, provenance, a human-readable clarified_spec, the slots asked,
    and the assumptions."""
    # 1. What did the original prompt already specify?
    detect = detect_fn or _default_detect_fn
    known: dict[str, str] = {k: str(v).strip() for k, v in (detect(seed_prompt) or {}).items()
                             if k in SLOT_KEYS and str(v).strip()}

    # 2. Ask ONLY the slots the prompt did not cover.
    to_ask = [s for s in SLOTS if s["key"] not in known]
    answered: dict[str, str] = {}
    for slot in to_ask:
        ans = (answer_fn(slot) or "").strip()
        if ans:
            answered[slot["key"]] = ans

    # 3. Slots still blank (prompt didn't cover, user didn't answer) -> LLM assumes.
    still_missing = [k for k in SLOT_KEYS if k not in known and k not in answered]
    assumed: dict[str, str] = {}
    if still_missing:
        fill = fill_fn or _default_fill_fn
        assumed = fill(seed_prompt, {**known, **answered}, still_missing) or {}

    slots: dict[str, dict] = {}
    for k in SLOT_KEYS:
        if k in known:
            slots[k] = {"source": "prompt", "value": known[k]}
        elif k in answered:
            slots[k] = {"source": "user", "value": answered[k]}
        else:
            slots[k] = {"source": "agent", "value": str(assumed.get(k, "(unspecified)")).strip()}

    return {
        "seed_prompt": seed_prompt,
        "slots": slots,
        "clarified_spec": format_clarified_spec(seed_prompt, slots),
        "asked": [s["key"] for s in to_ask],
        "assumptions": [f"{k}: {slots[k]['value']}" for k in still_missing],
    }


def format_clarified_spec(seed_prompt: str, slots: dict) -> str:
    """Render the filled slots into a spec string the planner can consume."""
    lines = [f"User request: {seed_prompt}", "", "Task specification:"]
    for slot in SLOTS:
        k = slot["key"]
        label = slot["question"].split(" -- ")[0]
        lines.append(f"- {label}: {slots[k]['value']}  [{slots[k]['source']}]")
    return "\n".join(lines)


# __ Default LLM gap-filler ____________________________________________________

def _default_detect_fn(seed_prompt: str) -> dict:
    """Ask an LLM which of the 6 slots the request ALREADY specifies.

    Returns {slot_key: value} only for slots clearly covered by the prompt;
    everything else is treated as missing and will be asked. This is what makes
    the Clarifier ask only the gaps, not all six questions."""
    import os as _os
    import re as _re
    from langchain_openai import ChatOpenAI
    from langchain_core.messages import SystemMessage, HumanMessage

    llm = ChatOpenAI(model=_os.getenv("MODEL_NAME", "claudeopus46"), streaming=True)
    slot_qs = "\n".join(f"- {s['key']}: {s['question']}" for s in SLOTS)
    sys = ("You inspect an underspecified scientific-workflow request and decide which "
           "fields it ALREADY specifies. Return ONLY a JSON object mapping each field key "
           "that the request clearly covers to a short string value. OMIT any field the "
           "request does not clearly specify -- do not guess. If the request specifies "
           "nothing concrete, return an empty object {}.")
    human = f"Request:\n{seed_prompt}\n\nFields:\n{slot_qs}"
    resp = llm.invoke([SystemMessage(content=sys), HumanMessage(content=human)])
    text = resp.content if hasattr(resp, "content") else str(resp)
    m = _re.search(r"\{.*\}", text, _re.DOTALL)
    if not m:
        return {}
    try:
        data = json.loads(m.group(0))
        return {k: str(v) for k, v in data.items() if k in SLOT_KEYS}
    except Exception:
        return {}


def _default_fill_fn(seed_prompt: str, answered: dict, missing: list) -> dict:
    """Ask an LLM to fill the missing slots with reasonable assumptions.
    Returns {slot_key: assumed_value} for the missing keys."""
    import os as _os
    import re as _re
    from langchain_openai import ChatOpenAI
    from langchain_core.messages import SystemMessage, HumanMessage

    llm = ChatOpenAI(model=_os.getenv("MODEL_NAME", "claudeopus46"), streaming=True)
    slot_qs = "\n".join(f"- {k}: {next(s['question'] for s in SLOTS if s['key'] == k)}"
                        for k in missing)
    answered_str = "\n".join(f"- {k}: {v}" for k, v in answered.items()) or "(none)"
    sys = ("You fill in the missing parts of an underspecified scientific-workflow request. "
           "For each missing field, make a single reasonable, concrete assumption consistent "
           "with the user's request and the fields they specified. Return ONLY a JSON object "
           "mapping each missing field key to a short string value.")
    human = (f"User request:\n{seed_prompt}\n\n"
             f"Fields the user already specified:\n{answered_str}\n\n"
             f"Missing fields to fill (respond with JSON for exactly these keys):\n{slot_qs}")
    resp = llm.invoke([SystemMessage(content=sys), HumanMessage(content=human)])
    text = resp.content if hasattr(resp, "content") else str(resp)
    m = _re.search(r"\{.*\}", text, _re.DOTALL)
    if not m:
        return {}
    try:
        data = json.loads(m.group(0))
        return {k: str(v) for k, v in data.items() if k in missing}
    except Exception:
        return {}
